# ---- a skipped arm must record under the name it would have used ------------
#
# #994. Sites skipped a whole block under ONE name that none of the arms inside
# it had. When the condition failed, those arms produced no record at all: a
# reader could not tell WHICH did not run, and the ledger could not tell a
# skipped arm from a deleted one, because a skipped arm's row has no matching
# record -- exactly as a removed check's would.
#
# The convention that fixes it was already in the tree: skip under each arm's own
# name, in a loop. This part asserts the loop stays in agreement with the arms.
#
# WHY A GUARD AND NOT JUST THE FIX. The loop DUPLICATES the arm names, so a rename
# in the sibling branch silently desynchronises them and the skip records under a
# name nothing emits -- the exact failure the fix exists to remove, reintroduced by
# an edit nobody thought was risky. Writing #994 I put into a loop a name that a
# DIFFERENT open PR renames, and this comparison is what caught it.
#
# EVERY LOOP, NOT THE FIRST ONE PER VARIABLE. The first version of this part
# extracted with an `exit` on first match, so a file with three loops over the same
# variable compared only the first -- and 340 has three (@OffgridwithJD). Worse,
# the one it compared was the one #994 had just written BOTH sides of, so it agreed
# by construction and examined nothing.
#
# THE GAP, STATED BECAUSE IT COVERS THE LOOP THIS CHANGE REPAIRS. `340`'s
# five-arm loop is NOT compared: its sibling arm is
# `check "an unreadable $_fp_n yields ..."`, generated by a loop over b.c and c.c,
# so a literal set comparison would report a false mismatch on a correct site.
# Driven: dropping a name from that loop is NOT caught, while dropping one from a
# comparable loop is. The count below is what makes that visible -- `interpolated 1`
# is a loop nobody checked, and a total of zero mismatches would otherwise read
# as a corpus in agreement.
#
# AND A COMPARISON IS ONLY MADE WHERE BOTH SIDES ARE LITERAL. `340`'s second loop
# has an INTERPOLATED sibling -- `check "an unreadable $_fp_n yields ..."` -- which
# is correct at runtime and would read as a mismatch to a literal set comparison.
# Those are counted and reported rather than silently dropped, because a comparison
# nobody makes and a comparison that passes look identical in a total.

_sk_py="$TESTDIR/../.github/scripts/skip-loop-arms.py"

check "premise: the sweep tool is present" \
	"$([ -r "$_sk_py" ] && echo yes || echo no)" "yes"

_sk_out="$(python3 "$_sk_py" "$TESTDIR" 2>&1)" || _sk_out="TOOL FAILED: $_sk_out"

_sk_loops=$(printf '%s\n' "$_sk_out"  | sed -n 's/^loops \([0-9]*\)$/\1/p')
_sk_cmp=$(printf '%s\n' "$_sk_out"    | sed -n 's/^compared \([0-9]*\)$/\1/p')
_sk_skip=$(printf '%s\n' "$_sk_out"   | sed -n 's/^interpolated \([0-9]*\)$/\1/p')
_sk_armless=$(printf '%s\n' "$_sk_out"| sed -n 's/^armless \([0-9]*\)$/\1/p')
_sk_bad="$(printf '%s\n' "$_sk_out"   | sed -n 's/^MISMATCH //p' | tr '\n' ' ' | sed 's/ $//')"

echo "-- skip loops: $_sk_loops found, $_sk_cmp compared, $_sk_skip interpolated, $_sk_armless armless"

# THE POPULATION IS THE PREMISE, twice over. A sweep that matched nothing reports
# the same zero mismatches as a corpus in agreement; and a sweep that found loops
# but compared none of them reports the same thing again.
check "premise: the sweep found skip loops at all" \
	"$([ "${_sk_loops:-0}" -ge 6 ] && echo yes || echo "only ${_sk_loops:-none}")" "yes"
check "premise: and it actually compared some of them" \
	"$([ "${_sk_cmp:-0}" -ge 4 ] && echo yes || echo "only ${_sk_cmp:-none}")" "yes"

check "every comparable skip loop names exactly the arms its sibling would emit (#994)" \
	"$_sk_bad" ""

unset _sk_py _sk_out _sk_loops _sk_cmp _sk_skip _sk_armless _sk_bad
